server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1024
spring:
  application:
    name: "matching-engine-ms"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
cors.allowed:
  - path: "/**"
    headers:
      - "*"
    origins:
      - "http://localhost:4200"
      - "http://localhost:8081"
      - "https://sgb-web-prod.azureedge.net"
    methods:
      - "HEAD"
      - "OPTIONS"
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
  - path: "/somePath/**"
    headers:
      - "*"
    origins:
      - "http://localhost:4200"
    methods:
      - "GET"
      - "POST"